name: "Abborre"

on:
  push:

jobs:
  gofmt:
    name: "go fmt"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4
      - uses: "actions/setup-go@v4"
        with:
          go-version-file: "./go.mod"

      - run: "test -z $(gofmt -l .)"

  govet:
    name: "go vet"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4
      - uses: "actions/setup-go@v4"
        with:
          go-version-file: "./go.mod"

      - run: "go vet ./..."

  gotest:
    name: "go test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4
      - uses: "actions/setup-go@v4"
        with:
          go-version-file: "./go.mod"

      - run: "go test ./..."

  tffmt:
    name: "tf fmt"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4
      - uses: "hashicorp/setup-terraform@v2"

      - run: "terraform fmt -check -diff -recursive"

  tfvalidate:
    name: "tf validate"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4
      - uses: "hashicorp/setup-terraform@v2"

      - run: "terraform init -backend=false"
        working-directory: "./infra"
      - run: "touch abborre-lambda.zip"
      - run: "terraform validate"
        working-directory: "./infra"

  deploy:
    needs: ["gofmt", "govet", "gotest", "tffmt", "tfvalidate"]
    if: "${{ github.ref == 'refs/heads/master' }}"
    name: "deploy ${{ matrix.env }}"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    strategy:
      matrix:
        include:
          - env: "test"
            url: "https://test.abborre.net"
          - env: "prod"
            url: "https://www.abborre.net"
    environment:
      name: "${{ matrix.env }}"
      url: "${{ matrix.url }}"
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4
      - uses: "aws-actions/configure-aws-credentials@v4"
        with:
          aws-region: "eu-north-1"
          role-to-assume: "arn:aws:iam::865405253382:role/GitHub-Actions"
          role-session-name: "GitHubActions-${{ matrix.env }}-deploy"

      - run: "./deploy.sh ${{ matrix.env }}"
